# Generated by Django 6.0.4 on 2026-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_country_user_id_alter_user_username_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
